# Generated by Django 5.0.6 on 2024-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
